In [191]:
import pandas as pd

pointsdf = pd.read_csv('../data/SaveLocation_CSV_2023_07_18_09_08_47-ofi.csv', usecols=['id', 'location name', 'date', 'group name'])
pointsdf['group name'].unique()

array(['Ida 8:10@!#ffff0000', 'Ida@!#ffff0000'], dtype=object)

In [192]:
pointsdf['datetime'] = pd.to_datetime(pointsdf['date'], format='%Y-%m-%d %H:%M:%S')
pointsdf

,id,location name,date,group name,datetime
0,159,Plaza Santiago,2023-07-18 09:03:18,Ida 8:10@!#ffff0000,2023-07-18 09:03:18
1,158,Puente Santiago,2023-07-18 09:00:14,Ida 8:10@!#ffff0000,2023-07-18 09:00:14
2,157,Centro Comercial Paraiso,2023-07-18 08:57:10,Ida 8:10@!#ffff0000,2023-07-18 08:57:10
3,156,Belen,2023-07-18 08:55:16,Ida 8:10@!#ffff0000,2023-07-18 08:55:16
4,155,Puente grau,2023-07-18 08:52:51,Ida 8:10@!#ffff0000,2023-07-18 08:52:51
...,...,...,...,...,...
68,125,Cachinayo,2023-07-18 08:16:30,Ida@!#ffff0000,2023-07-18 08:16:30
69,124,Puente Tupac Amaru,2023-07-18 08:15:32,Ida@!#ffff0000,2023-07-18 08:15:32
70,122,Universidad Andina,2023-07-18 08:14:55,Ida@!#ffff0000,2023-07-18 08:14:55
71,121,Teléfono,2023-07-18 08:14:17,Ida@!#ffff0000,2023-07-18 08:14:17
72,120,Tingo,2023-07-18 08:13:29,Ida@!#ffff0000,2023-07-18 08:13:29

In [193]:
p1 = pointsdf[pointsdf['group name'] == 'Ida@!#ffff0000']
p1 = p1.sort_values(by='datetime')
p1.reset_index(drop=True, inplace=True)
p1

,id,location name,date,group name,datetime
0,120,Tingo,2023-07-18 08:13:29,Ida@!#ffff0000,2023-07-18 08:13:29
1,121,Teléfono,2023-07-18 08:14:17,Ida@!#ffff0000,2023-07-18 08:14:17
2,122,Universidad Andina,2023-07-18 08:14:55,Ida@!#ffff0000,2023-07-18 08:14:55
3,124,Puente Tupac Amaru,2023-07-18 08:15:32,Ida@!#ffff0000,2023-07-18 08:15:32
4,125,Cachinayo,2023-07-18 08:16:30,Ida@!#ffff0000,2023-07-18 08:16:30
5,126,Enaco,2023-07-18 08:17:24,Ida@!#ffff0000,2023-07-18 08:17:24
6,129,Mercadillo,2023-07-18 08:19:21,Ida@!#ffff0000,2023-07-18 08:19:21
7,130,Santa rosa,2023-07-18 08:19:51,Ida@!#ffff0000,2023-07-18 08:19:51
8,133,Sexto,2023-07-18 08:21:42,Ida@!#ffff0000,2023-07-18 08:21:42
9,134,Quinto,2023-07-18 08:22:21,Ida@!#ffff0000,2023-07-18 08:22:21
10,135,Cuarto,2023-07-18 08:23:26,Ida@!#ffff0000,2023-07-18 08:23:26
11,136,Tercero,2023-07-18 08:24:50,Ida@!#ffff0000,2023-07-18 08:24:50
12,138,Callejon,2023-07-18 08:25:35,Ida@!#ffff0000,2023-07-18 08:25:35
13,139,Primero,2023-07-18 08:26:18,Ida@!#ffff0000,2023-07-18 08:26:18
14,140,Santa ursula,2023-07-18 08:27:31,Ida@!#ffff0000,2023-07-18 08:27:31
15,141,Marcavalle,2023-07-18 08:28:53,Ida@!#ffff0000,2023-07-18 08:28:53
16,142,Magisterio,2023-07-18 08:30:11,Ida@!#ffff0000,2023-07-18 08:30:11
17,143,Seminario,2023-07-18 08:30:57,Ida@!#ffff0000,2023-07-18 08:30:57
18,144,Prado,2023-07-18 08:32:24,Ida@!#ffff0000,2023-07-18 08:32:24
19,145,Hospital,2023-07-18 08:33:41,Ida@!#ffff0000,2023-07-18 08:33:41
20,146,Puerta Universidad Unsaac,2023-07-18 08:35:31,Ida@!#ffff0000,2023-07-18 08:35:31
21,147,Amauta,2023-07-18 08:37:44,Ida@!#ffff0000,2023-07-18 08:37:44
22,149,Colegio Garcilaso,2023-07-18 08:38:28,Ida@!#ffff0000,2023-07-18 08:38:28
23,150,Colegio Clorinda,2023-07-18 08:40:58,Ida@!#ffff0000,2023-07-18 08:40:58
24,151,Mercado Wanchaq,2023-07-18 08:42:35,Ida@!#ffff0000,2023-07-18 08:42:35
25,153,Estacion,2023-07-18 08:44:36,Ida@!#ffff0000,2023-07-18 08:44:36
26,154,Gradas,2023-07-18 08:45:32,Ida@!#ffff0000,2023-07-18 08:45:32
27,155,Puente Grau,2023-07-18 08:46:36,Ida@!#ffff0000,2023-07-18 08:46:36
28,156,Belen,2023-07-18 08:48:18,Ida@!#ffff0000,2023-07-18 08:48:18
29,157,Centro Comercial Paraiso,2023-07-18 08:50:15,Ida@!#ffff0000,2023-07-18 08:50:15
30,158,Puente Santiago,2023-07-18 08:52:30,Ida@!#ffff0000,2023-07-18 08:52:30
31,159,Plaza Santiago,2023-07-18 08:54:43,Ida@!#ffff0000,2023-07-18 08:54:43

In [194]:
tmp1 = p1.head(p1.shape[0]-1)
tmp1.reset_index(drop=True, inplace=True)
tmp2 = p1.tail(p1.shape[0]-1)[['id','location name', 'datetime']]
tmp2.rename(columns={'id':'id 2', 'location name': 'location name 2', 'datetime': 'datetime 2'}, inplace=True)
tmp2.reset_index(drop=True, inplace=True)
tt = pd.concat([tmp1, tmp2], axis=1)

tt['time'] = tt.apply(lambda row: (row['datetime 2'] - row['datetime']).total_seconds(), axis=1)
tt.drop(columns=['group name', 'date'], inplace=True)
tt = tt[['location name', 'location name 2', 'id', 'id 2', 'datetime', 'datetime 2', 'time']]
tt['step'] = tt['id 2'] - tt['id']
tt

,location name,location name 2,id,id 2,datetime,datetime 2,time,step
0,Tingo,Teléfono,120,121,2023-07-18 08:13:29,2023-07-18 08:14:17,48.0,1
1,Teléfono,Universidad Andina,121,122,2023-07-18 08:14:17,2023-07-18 08:14:55,38.0,1
2,Universidad Andina,Puente Tupac Amaru,122,124,2023-07-18 08:14:55,2023-07-18 08:15:32,37.0,2
3,Puente Tupac Amaru,Cachinayo,124,125,2023-07-18 08:15:32,2023-07-18 08:16:30,58.0,1
4,Cachinayo,Enaco,125,126,2023-07-18 08:16:30,2023-07-18 08:17:24,54.0,1
5,Enaco,Mercadillo,126,129,2023-07-18 08:17:24,2023-07-18 08:19:21,117.0,3
6,Mercadillo,Santa rosa,129,130,2023-07-18 08:19:21,2023-07-18 08:19:51,30.0,1
7,Santa rosa,Sexto,130,133,2023-07-18 08:19:51,2023-07-18 08:21:42,111.0,3
8,Sexto,Quinto,133,134,2023-07-18 08:21:42,2023-07-18 08:22:21,39.0,1
9,Quinto,Cuarto,134,135,2023-07-18 08:22:21,2023-07-18 08:23:26,65.0,1
10,Cuarto,Tercero,135,136,2023-07-18 08:23:26,2023-07-18 08:24:50,84.0,1
11,Tercero,Callejon,136,138,2023-07-18 08:24:50,2023-07-18 08:25:35,45.0,2
12,Callejon,Primero,138,139,2023-07-18 08:25:35,2023-07-18 08:26:18,43.0,1
13,Primero,Santa ursula,139,140,2023-07-18 08:26:18,2023-07-18 08:27:31,73.0,1
14,Santa ursula,Marcavalle,140,141,2023-07-18 08:27:31,2023-07-18 08:28:53,82.0,1
15,Marcavalle,Magisterio,141,142,2023-07-18 08:28:53,2023-07-18 08:30:11,78.0,1
16,Magisterio,Seminario,142,143,2023-07-18 08:30:11,2023-07-18 08:30:57,46.0,1
17,Seminario,Prado,143,144,2023-07-18 08:30:57,2023-07-18 08:32:24,87.0,1
18,Prado,Hospital,144,145,2023-07-18 08:32:24,2023-07-18 08:33:41,77.0,1
19,Hospital,Puerta Universidad Unsaac,145,146,2023-07-18 08:33:41,2023-07-18 08:35:31,110.0,1
20,Puerta Universidad Unsaac,Amauta,146,147,2023-07-18 08:35:31,2023-07-18 08:37:44,133.0,1
21,Amauta,Colegio Garcilaso,147,149,2023-07-18 08:37:44,2023-07-18 08:38:28,44.0,2
22,Colegio Garcilaso,Colegio Clorinda,149,150,2023-07-18 08:38:28,2023-07-18 08:40:58,150.0,1
23,Colegio Clorinda,Mercado Wanchaq,150,151,2023-07-18 08:40:58,2023-07-18 08:42:35,97.0,1
24,Mercado Wanchaq,Estacion,151,153,2023-07-18 08:42:35,2023-07-18 08:44:36,121.0,2
25,Estacion,Gradas,153,154,2023-07-18 08:44:36,2023-07-18 08:45:32,56.0,1
26,Gradas,Puente Grau,154,155,2023-07-18 08:45:32,2023-07-18 08:46:36,64.0,1
27,Puente Grau,Belen,155,156,2023-07-18 08:46:36,2023-07-18 08:48:18,102.0,1
28,Belen,Centro Comercial Paraiso,156,157,2023-07-18 08:48:18,2023-07-18 08:50:15,117.0,1
29,Centro Comercial Paraiso,Puente Santiago,157,158,2023-07-18 08:50:15,2023-07-18 08:52:30,135.0,1
30,Puente Santiago,Plaza Santiago,158,159,2023-07-18 08:52:30,2023-07-18 08:54:43,133.0,1

In [195]:
from datetime import datetime, time, timedelta
def redondear_hora(dt, split):
    m = int(round(dt.time().minute/split, 0))*split
    if m == 60 or dt.time().hour == 4: 
        return time(dt.time().hour + 1, 0)   
    else:
        return time(dt.time().hour, m)

#  Aproximar la 'hora' en intervalos de tiempo n minutos
n = 15
name_col = 'rg' + str(n)+'min'
tt[name_col] = tt['datetime 2'].apply(redondear_hora, split=n)

# dividir las horas y minutos en diferentes columnas
tt['horas'] = tt['rg15min'].apply(lambda t: t.hour)
tt['minute'] = tt['rg15min'].apply(lambda t: t.minute)
tt['location name'] = tt['location name'] + ' - ' + tt['location name 2']
tt['str'] = 'min'
tt['id'] = tt['id'] - 100
tt['id 2'] = tt['id 2'] - 100
tt = tt[['location name','id','id 2','time', 'horas','minute', 'str','step']]
tt

,location name,id,id 2,time,horas,minute,str,step
0,Tingo - Teléfono,20,21,48.0,8,15,min,1
1,Teléfono - Universidad Andina,21,22,38.0,8,15,min,1
2,Universidad Andina - Puente Tupac Amaru,22,24,37.0,8,15,min,2
3,Puente Tupac Amaru - Cachinayo,24,25,58.0,8,15,min,1
4,Cachinayo - Enaco,25,26,54.0,8,15,min,1
5,Enaco - Mercadillo,26,29,117.0,8,15,min,3
6,Mercadillo - Santa rosa,29,30,30.0,8,15,min,1
7,Santa rosa - Sexto,30,33,111.0,8,15,min,3
8,Sexto - Quinto,33,34,39.0,8,15,min,1
9,Quinto - Cuarto,34,35,65.0,8,30,min,1
10,Cuarto - Tercero,35,36,84.0,8,30,min,1
11,Tercero - Callejon,36,38,45.0,8,30,min,2
12,Callejon - Primero,38,39,43.0,8,30,min,1
13,Primero - Santa ursula,39,40,73.0,8,30,min,1
14,Santa ursula - Marcavalle,40,41,82.0,8,30,min,1
15,Marcavalle - Magisterio,41,42,78.0,8,30,min,1
16,Magisterio - Seminario,42,43,46.0,8,30,min,1
17,Seminario - Prado,43,44,87.0,8,30,min,1
18,Prado - Hospital,44,45,77.0,8,30,min,1
19,Hospital - Puerta Universidad Unsaac,45,46,110.0,8,30,min,1
20,Puerta Universidad Unsaac - Amauta,46,47,133.0,8,30,min,1
21,Amauta - Colegio Garcilaso,47,49,44.0,8,45,min,2
22,Colegio Garcilaso - Colegio Clorinda,49,50,150.0,8,45,min,1
23,Colegio Clorinda - Mercado Wanchaq,50,51,97.0,8,45,min,1
24,Mercado Wanchaq - Estacion,51,53,121.0,8,45,min,2
25,Estacion - Gradas,53,54,56.0,8,45,min,1
26,Gradas - Puente Grau,54,55,64.0,8,45,min,1
27,Puente Grau - Belen,55,56,102.0,8,45,min,1
28,Belen - Centro Comercial Paraiso,56,57,117.0,8,45,min,1
29,Centro Comercial Paraiso - Puente Santiago,57,58,135.0,8,45,min,1
30,Puente Santiago - Plaza Santiago,58,59,133.0,9,0,min,1

In [197]:
#tt.to_csv('pruebasCampo1.csv', index=False)